name: Diffblue Cover (activate)
description: Component action for running "dcover activate", used for custom workflows in complex projects.
author: Diffblue
inputs:
  license-key:
    required: true
    description: The license key provided in your welcome email or provided by your organization
  working-directory:
    required: false
    description: The working directory to pass to `dcover` comamnds that accept a `--working-directory` argument.
  topic-id-differentiator:
    required: false
    description: Optional string to differentiate multiple uses of the actions within a single workflow.
runs:
  using: node16
  main: ../dist/activate/index.js
