name: Diffblue Cover (validate)
description: Component action for running "dcover validate", used for custom workflows in complex projects.
author: Diffblue
inputs:
  working-directory:
    required: false
    description: The working directory to pass to `dcover` comamnds that accept a `--working-directory` argument.
  commit-and-push:
    required: false
    description: 'true' or '' if the commands should commit and push changes back to the branch.
  validate-args:
    required: false
    description: Additional command line arguments for the `dcover validate` command.
  topic-id-differentiator:
    required: false
    description: Optional string to differentiate multiple uses of the actions within a single workflow.
runs:
  using: node16
  main: ../dist/validate/index.js
