name: Diffblue Cover (install)
description: Component action for installing Diffblue Cover, used for custom workflows in complex projects.
author: Diffblue
inputs:
  license-key:
    required: true
    description: The license key provided in your welcome email or provided by your organization
  user-name:
    required: true
    description: The name of the commit author, used to configure the git `user.name`.
  user-email:
    required: true
    description: The email address of the commit author, used to configure the git `user.name`.
  working-directory:
    required: false
    description: The working directory to pass to `dcover` comamnds that accept a `--working-directory` argument.
  topic-id-differentiator:
    required: false
    description: Optional string to differentiate multiple uses of the actions within a single workflow.
runs:
  using: node16
  main: ../dist/install/index.js
