name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check - Description Length
        uses: mikefarah/yq@master
        with:
          cmd: yq eval --exit-status '.description | length < 125' action.yml

      - name: Build
        run: |
          # Rebuild per-JDK actions based on the base content
          ./build.sh

          # Fail CI if rebuilding left uncommitted changes
          if [ "$(git status --porcelain | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git status
            exit 1
          fi
