name: "Test: Custom Project"

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

concurrency:

  # Avoid running the same workflow on the same branch concurrently
  group: ${{ github.workflow }}-${{ github.ref }}

  # Cancel previous runs of the workflow unless running on the main branch
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  Test:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [windows-latest]

    defaults:
      run:
        working-directory: ./test
        
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # The default GITHUB_TOKEN doesn't have the necessary permissions
          # so a custom token should be used here with sufficient access.
          token: ${{ secrets.DIFFBLUE_TOKEN }}
          # By default the merge commit is checked out, but here we want
          # the HEAD SHA in preparation for adding commits to the branch.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Git Config
        # Adding commits to the branch requires an author name and email address.
        run: |
          git config user.name "Diffblue CI"
          git config user.email "db-ci-platform@diffblue.com"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Diffblue Cover (install)
        uses: ./install/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # User name and email used to author commits
          user-name: Diffblue CI
          user-email: db-ci-platform@diffblue.com
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}

      - name: Diffblue Cover (activate)
        uses: ./activate/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # License key used to activate the installation
          license-key: ${{ secrets.DIFFBLUE_LICENSE_KEY }}
          # User name and email used to author commits
          user-name: Diffblue CI
          user-email: db-ci-platform@diffblue.com
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}
      
      - name: Gradle Build
        run: ./gradlew --console plain build
        working-directory: ./test/gradle-project

      - name: Diffblue Cover (clean)
        uses: ./clean/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # User name and email used to author commits
          user-name: Diffblue CI
          user-email: db-ci-platform@diffblue.com
          # Integration test project lives in a subdir
          working-directory: ./test/gradle-project
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}

      - name: Diffblue Cover (validate)
        uses: ./validate/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # User name and email used to author commits
          user-name: Diffblue CI
          user-email: db-ci-platform@diffblue.com
          # Integration test project lives in a subdir
          working-directory: ./test/gradle-project
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}

      - name: Diffblue Cover (create)
        uses: ./create/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # User name and email used to author commits
          user-name: Diffblue CI
          user-email: db-ci-platform@diffblue.com
          # Integration test project lives in a subdir
          working-directory: ./test/gradle-project
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}
      
      - name: Git Push
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: git push origin HEAD:${{ github.event.pull_request.head.ref }}

      - name: Diffblue Cover (summary)
        uses: ./summary/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # User name and email used to author commits
          user-name: Diffblue CI
          user-email: db-ci-platform@diffblue.com
          # Integration test project lives in a subdir
          working-directory: ./test/gradle-project
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}
