name: "Test: Maven Project"

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:

  Test:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

    defaults:
      run:
        working-directory: ./test/maven-project
        
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Maven Install
        run: mvn --batch-mode install
  
      - name: Diffblue Cover
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          # License key used to activate the installation
          license-key: ${{ secrets.DIFFBLUE_LICENSE_KEY }}
          # User name and email used to author commits
          user-name: Diffblue CI
          user-email: db-ci-platform@diffblue.com
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}
