name: "Test: Gradle Project"

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:

  Test:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

    defaults:
      run:
        working-directory: ./test/gradle-project
        
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Gradle Build
        run: ./gradlew --console plain build

      - name: Diffblue Cover
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          license-key: ${{ secrets.DIFFBLUE_LICENSE_KEY }}
          topic-id-differentiator: ${{ matrix.os }}
