name: "Test: Custom Project"

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:

  Test:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

    defaults:
      run:
        working-directory: ./test
        
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # The default GITHUB_TOKEN doesn't have the necessary permissions
          # so a custom token should be used here with sufficient access.
          token: ${{ secrets.DIFFBLUE_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Diffblue Cover (install)
        uses: ./install/
        env:
          GITHUB_TOKEN: ${{ secrets.DIFFBLUE_TOKEN }}
          JVM_ARGS: -Xmx4096m
        with:
          # User name and email used to author commits
          user-name: Diffblue CI
          user-email: db-ci-platform@diffblue.com
          # Add a differentiator based on the matrix
          topic-id-differentiator: ${{ matrix.os }}
